version: '3.8'
services:
  app:
    build: .
    container_name: hr-cms-app
    env_file:
      - .env
    ports:
      - "3000:3000"
    depends_on:
      - mongo

  mongo:
    image: mongo:6.0
    container_name: hr-cms-mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: hr_db
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
