flow_management_task:
  description: >
    Manage the interview process by tracking its state based on conversation history and skill evaluations. The interview progresses through three stages:

    1. **Welcome Stage** (`"state": "welcome"`)
       - Activated when conversation history is empty.

    2. **Ongoing Stage** (`"state": "ongoing"`)
       - Active when at least one skill requires further evaluation:
         - Skill has <3 questions asked AND
         - Skill has average rating ≤8 (or no rating)

    3. **Completed Stage** (`"state": "completed"`)
       - Triggered when ALL skills meet either:
         - ≥3 questions asked, OR
         - Average rating >8 (early positive conclusion)

    **Input References:**
    - **Conversation History:** `{conversation_history}`
    - **Skills Dictionary:** `{skills}`
    
  expected_output: >
    Returns a JSON string indicating the current interview state:
    - `{"state": "welcome"}`
    - `{"state": "ongoing"}`
    - `{"state": "completed"}`

    Output must be plain JSON without markdown formatting.

  agent: flow_manager