flow_management_task:
  description: >
    **Interview Stages:**

      * **Welcome:** The interview has just begun. No questions have been asked.
      * **Ongoing:** Active questioning and skill evaluation are in progress.
      * **Completed:** All required skill evaluations are finished.
      **Stage Determination Rules:**

      1.  **Welcome:** If the `conversation_history` is empty, the interview is in the "welcome" stage.
      2.  **Ongoing:** If the `conversation_history` is not empty, the interview is in the "ongoing" stage, *unless* the "completed" criteria are met.
      3.  **Completed:** The interview is "completed" when **all** skills meet **one** of these criteria:
          * At least 3 questions have been asked about the skill.
          * The average rating for the skill is greater than 8.

      **Skill Evaluation Criteria (Ongoing Stage):**

      * A skill is considered "ongoing" if:
          * Fewer than 3 questions have been asked about it, **AND**
          * The average rating for the skill is 8 or less, or there is no rating.

      **Input Data:**

      * **Conversation History:** `{conversation_history}`
      * **Skills Dictionary:** `{skills}`

  expected_output: >
    Returns a JSON string indicating the current interview state:
    - `{"state": "welcome"}`
    - `{"state": "ongoing"}`
    - `{"state": "completed"}`

    Output must be plain JSON without markdown formatting.

  agent: flow_manager