services:
  # app:
  #   build: .
  #   container_name: nest-app
  #   env_file: .env
  #   ports:
  #     - "3000:3000"
  #   depends_on:
  #     - mongo

  mongo:
    image: mongo:latest
    container_name: nest-mongo
    environment:
      MONGO_INITDB_DATABASE: hr_cms_db
    ports:
      - '27017:27017'
    volumes:
      - mongo_data:/data/db
      
volumes:
  mongo_data:
