name: Run Jest Tests for API Gateway

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: 'services/cms/backend/package-lock.json'

      - name: Install Dependencies
        working-directory: services/cms/backend
        run: npm install

      - name: Run Jest Tests
        working-directory: services/cms/backend
        run: npx jest
