name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup SSH agent
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}
      
      - name: Copy files to EC2
        run: |
          rsync -avz --exclude '.git*' --exclude 'node_modules' ./ ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}:/home/${{ secrets.EC2_USER }}/app
        env:
          RSYNC_RSH: "ssh -o StrictHostKeyChecking=no"

      - name: Deploy via SSH
        run: |
            ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
              cd /home/${{ secrets.EC2_USER }}/app
              # Optionally pull latest changes if not using rsync
              # git pull origin main
              docker-compose down
              docker-compose up -d --build
            EOF